### ISSUE TITLE
是否通过wifi连接？

### ISSUE THREAD

**Issue by edsion1107** [openatx/weditor#10]
```
[I 180103 16:00:06 web:2063] 304 GET /api/v1/version (::1) 1.79ms
[I 180103 16:00:09 web:2063] 200 POST /api/v1/connect (::1) 107.96ms
SN 3039ec4f-443a-4d6f-a079-9336c5d26500
Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1152ef2e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='d9d53d2e', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1152ef2e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/weditor/__main__.py", line 134, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 668, in screenshot
    r = requests.get(self.server.screenshot_uri)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='d9d53d2e', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1152ef2e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
[W 180103 16:00:12 web:2063] 430 GET /api/v1/devices/3039ec4f-443a-4d6f-a079-9336c5d26500/screenshot (::1) 30.53ms
^Cexiting...
exit success
edsiondeMacBook-Pro:yyb edsion$ python -m weditor 17310
listen port 17310
[I 180103 16:02:06 web:2063] 304 GET /api/v1/version (::1) 2.25ms
[I 180103 16:02:09 web:2063] 200 POST /api/v1/connect (::1) 85.90ms
SN 1722a09c-067d-4502-b4e8-5672730b7189
Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10f5832e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='d9d53d2e', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f5832e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/weditor/__main__.py", line 134, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 668, in screenshot
    r = requests.get(self.server.screenshot_uri)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='d9d53d2e', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f5832e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
[W 180103 16:02:11 web:2063] 430 GET /api/v1/devices/1722a09c-067d-4502-b4e8-5672730b7189/screenshot (::1) 17.97ms

```

错误信息如上，是否因为我的pc和手机在同一网段导致的？怎么才能走USB呢

**Comment by codeskyblue** [comment]
升级weditor 直接填设备序列号

**Comment by edsion1107** [comment]
目前的log：

`listen port 17310
[I 180103 18:29:56 web:2087] 304 GET /api/v1/version (::1) 3.17ms
[I 180103 18:29:58 web:2087] 200 POST /api/v1/connect (::1) 34.98ms
SN 0f8c1efe-3b6f-4a66-a680-f2ecacf6a978
Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11013e7b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='df586f75', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11013e7b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/weditor/__main__.py", line 134, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/uiautomator2/__init__.py", line 668, in screenshot
    r = requests.get(self.server.screenshot_uri)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/edsion/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='df586f75', port=7912): Max retries exceeded with url: /screenshot/0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11013e7b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
[W 180103 18:30:01 web:2087] 430 GET /api/v1/devices/0f8c1efe-3b6f-4a66-a680-f2ecacf6a978/screenshot (::1) 13.59ms`

我的环境如下：

`aircv==1.4.6
atx==1.1.3.dev36
atx-uiautomator==0.3.3
AxmlParserPY==0.0.3
beautifulsoup4==4.6.0
certifi==2017.11.5
chardet==3.0.4
colorama==0.3.9
cycler==0.10.0
et-xmlfile==1.0.1
facebook-wda==0.2.2.dev1
fire==0.1.2
futures==3.0.5
humanize==0.5.1
idna==2.6
imageio==2.2.0
jdcal==1.3
lxml==4.1.1
maproxy==0.0.12
matplotlib==2.1.1
numpy==1.14.0rc1
odfpy==1.3.6
olefile==0.44
opencv-python==3.4.0.12
openpyxl==2.4.9
Pillow==5.0.0
progress==1.3
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.11
requests==2.18.4
requests-toolbelt==0.8.0
selenium==3.8.0
six==1.11.0
tablib==0.12.1
tornado==5.0a1
tqdm==4.5.0
uiautomator2==0.0.2
unicodecsv==0.14.1
urllib3==1.22
weditor==0.0.4.dev6
xlrd==1.1.0
xlwt==1.3.0`

[](https://ws3.sinaimg.cn/large/006tKfTcly1fn3lmusdtlj30td0hbwgc.jpg)
目前还是无法正常工作

**Comment by edsion1107** [comment]
![2018-01-03 6 32 42](https://user-images.githubusercontent.com/1925286/34517153-cdde52cc-f0b4-11e7-9453-4ecf97ee64ea.png)

**Comment by codeskyblue** [comment]
忘了说了，这玩意依赖的是uiautomator2

**Comment by codeskyblue** [comment]
哎，我的错

**Comment by edsion1107** [comment]
uiautomator2==0.0.2
uiautomator2我有安装啊

**Comment by codeskyblue** [comment]
uiautomator2==0.0.3.dev22

**Comment by codeskyblue** [comment]
https://github.com/openatx/uiautomator2

**Comment by edsion1107** [comment]
uiautomator2==0.0.2
weditor==0.0.4.dev6
我把__main__.py第243行`d = u2.connect(device_url)`改成`d = u2.connect_usb(device_url)`发现就可以用了。
更新到uiautomator2==0.0.3.dev22又会报其它的错误了

**Comment by codeskyblue** [comment]
会报什么错？贴出来看看
