### ISSUE TITLE
IOError: cannot identify image file <_io.BytesIO object at 0x039CAEA0>

### ISSUE THREAD

**Issue by NextOneWxf** [openatx/weditor#15]
![image](https://user-images.githubusercontent.com/4550421/38595498-c01dbb8e-3d7e-11e8-98b1-bb17709d2371.png)

**Comment by freedom-wy** [comment]
我也遇到了这个问题
`
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\weditor\__main__.py", line 137, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "<decorator-gen-4>", line 2, in screenshot
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\uiautomator2\__init__.py", line 1491, in screenshot
    return Image.open(buff)
  File "D:\Program Files (x86)\Python36-32\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x04EB0DE0>
`

目前还没解决

**Comment by codeskyblue** [comment]
我这复现不了

**Comment by freedom-wy** [comment]
重新初始化解决了问题

**Comment by slightun** [comment]
我也出现了这个问题。 但是重新初始化也解决不了。

**Comment by zhizunbao84** [comment]
我也出现了这个问题。 但是重新初始化也解决不了。
而且挺奇怪的，我家里一天电脑使用没有出现任何问题，但是到单位，确怎么弄都不行
这个跟win7的权限管理有关系吗。我家里电脑没开UAC，单位的电脑开了UAC，别的没啥区别啦

**Comment by zhizunbao84** [comment]
![222222222](https://user-images.githubusercontent.com/2263408/66361384-3047b600-e9b1-11e9-8047-e719b6443c99.png)

**Comment by bluerheaven** [comment]
重启手机解决了

**Comment by pahoehoe** [comment]
关掉“可以让你使用更多网络的工具”，我猜你那个工具开的全局模式。
我今天也遇到这个问题了，然后重新启动weditor发现一行log：
Unknown error: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=1080): Read timed out. (read timeout=2.0)"))
就好奇为啥本地地址都连不上，突然反应过来应该是开了"全局模式"。。
