### ISSUE TITLE
Uncaught exception GET /api/v1/devices/9bbce60b-648e-406d-a521-e87b959e0f57/hierarchy

### ISSUE THREAD

**Issue by q88535448** [openatx/weditor#18]
```
[E 180511 13:04:43 web:1590] Uncaught exception GET /api/v1/devices/9bbce60b-648e-406d-a521-e87b959e0f57/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/9bbce60b-648e-406d-a521-e87b959e0f57/hierarchy', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://atx.open.netease.com', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:17310', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6', 'Connection': 'keep-alive', 'Referer': 'http://atx.open.netease.com/'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/site-packages/weditor/__main__.py", line 271, in get
        self.write(uidumplib.get_ios_hierarchy(d))
      File "/usr/local/lib/python2.7/site-packages/weditor/uidumplib.py", line 126, in get_ios_hierarchy
        sourcejson = d._wda.source(format='json')
    TypeError: source() got an unexpected keyword argument 'format'
```

WDA的source方法是这样的
```
def source(self, accessible=False):
        if accessible:
            return self._request('/wda/accessibleSource', 'GET').value
        return self._request('source', 'GET').value
```
貌似不能接收format啊？

```
def get_ios_hierarchy(d):
    sourcejson = d._wda.source()
    def travel(node):
        node['id'] = str(uuid.uuid4())
        if node.get('rect'):
            rect = node['rect']
            nrect = {}
            for k, v in rect.items():
                nrect[k] = v*d.scale
            node['rect'] = nrect
            
        for child in node.get('children', []):
            travel(child)
        return node

    return travel(sourcejson)
```

而且这里的node我获得的是一个unicode格式对象，并不是字典？

**Comment by q88535448** [comment]
更新以后好了，请忽略
