### ISSUE TITLE
我在用安卓手机测试 当页面出现跳转时就报这个错，求解

### ISSUE THREAD

**Issue by qinghuazhu** [openatx/weditor#2]
C:\Users\qinghua>python -m weditor
listen port 17310
[W 170610 12:14:31 web:1946] 404 GET /api/v1/contents/main.py (::1) 1.00ms
[I 170610 12:14:31 web:1946] 304 GET /api/v1/version (::1) 1.00ms
SN default
[I 170610 12:14:43 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:14:44 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:14:45 web:1946] 200 GET /api/v1/devices/default/screenshot (::1) 2232.00ms
[I 170610 12:14:45 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:14:46 web:1946] 200 GET /api/v1/devices/default/uiview (::1) 151.00ms
SN default
[I 170610 12:17:18 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:17:18 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:17:20 web:1946] 200 GET /api/v1/devices/default/screenshot (::1) 2257.00ms
[I 170610 12:17:20 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:17:20 web:1946] 200 GET /api/v1/devices/default/uiview (::1) 138.00ms
[W 170610 12:31:26 web:1946] 404 GET /api/v1/contents/main.py (::1) 1.00ms
[I 170610 12:31:26 web:1946] 304 GET /api/v1/version (::1) 1.00ms
SN default
[I 170610 12:31:27 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:27 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:31:27.946 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:31:28 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:28 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:31:28 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 1147.00ms
SN default
[I 170610 12:31:32 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:31:33.202 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:31:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:31:33 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 989.00ms
SN default
[I 170610 12:31:38 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:38 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:31:38.652 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:31:38 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:31:39 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:31:39 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 1106.00ms
[W 170610 12:31:55 web:1946] 404 GET /api/v1/contents/main.py (::1) 0.00ms
[I 170610 12:31:55 web:1946] 304 GET /api/v1/version (::1) 1.00ms
SN default
[I 170610 12:32:05 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:06 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:32:06.059 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:32:06 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:06 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:32:06 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 1113.00ms
[W 170610 12:32:29 web:1946] 404 GET /api/v1/contents/main.py (::1) 1.00ms
[I 170610 12:32:29 web:1946] 304 GET /api/v1/version (::1) 0.00ms
SN default
[I 170610 12:32:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:32:33.700 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:32:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:34 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:32:34 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 1110.00ms
SN default
[I 170610 12:32:50 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:50 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:51 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:52 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:52 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:32:52.403 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:32:52 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:32:52 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
IOError: Screenshot use uiautomator failed.
[W 170610 12:32:52 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 3699.00ms
[W 170610 12:38:30 web:1946] 404 GET /api/v1/contents/main.py (::1) 1.00ms
[I 170610 12:38:30 web:1946] 304 GET /api/v1/version (::1) 0.00ms
SN default
[I 170610 12:38:32 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:38:32 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
2017-06-10 12:38:32.951 WARN  [atx.drivers.mixin: 390] warning, screenshot failed [2/1], retry again
[I 170610 12:38:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
[I 170610 12:38:33 connectionpool:203] Starting new HTTP connection (1): 127.0.0.1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 123, in get
    d.screenshot().save(buffer, format='JPEG')
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 62, in _inner
    _retval = fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\drivers\mixin.py", line 391, in screenshot
    screen = self._take_screenshot()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 282, in _take_screenshot
    screen = self._screenshot_uiauto()
  File "C:\Python27\lib\site-packages\atx\drivers\android.py", line 254, in _screenshot_uiauto
    raise IOError("Screenshot use uiautomator failed.")
**IOError: Screenshot use uiautomator failed.**
[W 170610 12:38:33 web:1946] 430 GET /api/v1/devices/default/screenshot (::1) 1114.00ms

![image](https://user-images.githubusercontent.com/22891449/27000026-2e333eae-4dda-11e7-98d1-d31daeaa2f05.png)

**Comment by codeskyblue** [comment]
截图不支持，不如换个手机试试
