### ISSUE TITLE
api/v1/devices/aafcfc06-b0d1-430c-808a-ec834d13532c/screenshot 430 error

### ISSUE THREAD

**Issue by chenjiacun35** [openatx/weditor#26]
python:2.7.15
PIL:1.1.7
Pillow:5.2.0
weditor：0.0.4.dev17
错误信息：
```
Request URL: http://localhost:17310/api/v1/devices/aafcfc06-b0d1-430c-808a-ec834d13532c/screenshot
Request Method: GET

Status Code: 430 Environment Error
```

错误堆栈信息：
```
Traceback (most recent call last):
  File "D:\Program Files\Python2.7.5\lib\site-packages\weditor\__main__.py", lin
e 137, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "D:\Program Files\Python2.7.5\lib\site-packages\PIL\Image.py", line 1439,
 in save
    save_handler(self, fp, filename)
  File "D:\Program Files\Python2.7.5\lib\site-packages\PIL\JpegImagePlugin.py",
line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "D:\Program Files\Python2.7.5\lib\site-packages\PIL\ImageFile.py", line 4
76, in _save
    fh = fp.fileno()
UnsupportedOperation: fileno
```
描述：
点击connect连接上设备后，再点击reload出错

**Comment by codeskyblue** [comment]
把pil卸载了，pillow重装下试试
