### ISSUE TITLE
win7 64为，python34 安装失败

### ISSUE THREAD

**Issue by liang3179** [openatx/weditor#43]
使用win7 64位系统，python版本为：3.4.3 PIP版本为：19.1 
执行pip install --pre --upgrade weditor失败，不能成功安装，是因为不支持python3.4版本吗？
错误如下：
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last o
ne supporting it. Please upgrade your Python as Python 3.4 won't be maintained a
fter March 2019 (cf PEP 429).
Collecting weditor
  Using cached https://files.pythonhosted.org/packages/3c/a4/ada9d143126fec45b54
e745eb26631d9b87c0342251e1190bafa977718dc/weditor-0.1.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR:
    Installed c:\users\s10575\appdata\local\temp\pip-install-g856rq6f\weditor\.e
ggs\pbr-5.1.3-py3.4.egg
    E:\Python34\Lib\site-packages\pkg_resources\__init__.py:2510: PEP440Warning:
 'pbr (0.5.2.5.g5b3e942)' is being parsed as a legacy, non PEP 440, version. You
 may find odd behavior and sort order. In particular it will be sorted as less t
han 0.0. It is recommend to migrate to PEP 440 compatible versions.
      PEP440Warning,
    E:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution opt
ion: 'project_urls'
      warnings.warn(msg)
    E:\Python34\Lib\distutils\dist.py:260: UserWarning: Unknown distribution opt
ion: 'long_description_content_type'
      warnings.warn(msg)
    Marker evaluation failed, see the following error.  For more information see
: http://docs.openstack.org/pbr/latest/user/using.html#environment-markers
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1447,
 in comparison
        cop = cls.get_op(cop)
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1467,
 in get_op
        return ops[op]
    KeyError: '<='

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\s10575\appdata\local\temp\pip-install-g856rq6f\weditor\.egg
s\pbr-5.1.3-py3.4.egg\pbr\core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "c:\users\s10575\appdata\local\temp\pip-install-g856rq6f\weditor\.egg
s\pbr-5.1.3-py3.4.egg\pbr\util.py", line 258, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "c:\users\s10575\appdata\local\temp\pip-install-g856rq6f\weditor\.egg
s\pbr-5.1.3-py3.4.egg\pbr\util.py", line 456, in setup_cfg_to_setup_kwargs
        if pkg_resources.evaluate_marker('(%s)' % env_marker):
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1481,
 in evaluate_marker
        return cls.interpret(parser.expr(text).totuple(1)[1])
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1515,
 in interpret
        return op(nodelist)
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1429,
 in atom
        return cls.interpret(nodelist[2])
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1515,
 in interpret
        return op(nodelist)
      File "E:\Python34\Lib\site-packages\pkg_resources\__init__.py", line 1450,
 in comparison
        raise SyntaxError(msg)
      File "<string>", line None
    SyntaxError: '<=' operator not allowed in environment markers
    error in setup command: Error parsing C:\Users\s10575\AppData\Local\Temp\pip
-install-g856rq6f\weditor\setup.cfg: SyntaxError: '<=' operator not allowed in e
nvironment markers
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\s
10575\AppData\Local\Temp\pip-install-g856rq6f\weditor\

**Comment by liang3179** [comment]
升级到python3.7.3版本，该问题消失
