### ISSUE TITLE
Python2.7.12使用weditor报python -m weditor

### ISSUE THREAD

**Issue by seiyasaga** [openatx/weditor#46]
cmd执行python -m weditor报python -m weditor

**Comment by seiyasaga** [comment]
C:\Python27\Scripts>python -m weditor
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 22, in <module>

    import tornado.ioloop
  File "C:\Python27\lib\site-packages\tornado\ioloop.py", line 67
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax
