### ISSUE TITLE
Python2.7.12使用weditor报SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by seiyasaga** [openatx/weditor#47]
cmd执行python -m weditor报错SyntaxError: invalid syntax
C:\Python27\Scripts>python -m weditor
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\weditor\__main__.py", line 22, in <module>

    import tornado.ioloop
  File "C:\Python27\lib\site-packages\tornado\ioloop.py", line 67
    def fileno(self) -> int:
                          ^
SyntaxError: invalid syntax

**Comment by seiyasaga** [comment]
@codeskyblue

**Comment by codeskyblue** [comment]
估计是新版tornado不支持python2.7了，现在越来越多的库不支持python2了，建议换到python3吧。

**Comment by seiyasaga** [comment]
好的，谢谢，一直用的python2，看来要更新python3了。
