### ISSUE TITLE
dump hierarchy error

### ISSUE THREAD

**Issue by shigubuhua** [openatx/weditor#49]
连接mumu模拟器时，connect后，点击dump hierarchy，出现提示：
`local server not started, start with
 python -m weditor`
weditor并未退出，命令行提示：
`[I 190701 17:00:45 web:2246] 200 GET /api/v1/devices/android%3A127.0.0.1%3A7555/screenshot (::1) 4677.18ms
[W 190701 17:00:45 session:477] request error: 404 page not found

[E 190701 17:00:45 web:1788] Uncaught exception GET /api/v1/devices/android%3A127.0.0.1%3A7555/hierarchy (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/api/v1/devices/android%3A127.0.0.1%3A7555/hierarchy', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\tornado\web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\weditor\web\handlers\page.py", line 171, in get
        self.write(d.dump_hierarchy())
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\weditor\web\device.py", line 17, in dump_hierarchy
        return uidumplib.get_android_hierarchy(self._d)
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\weditor\web\uidumplib.py", line 107, in get_android_hierarchy
        page_xml = d.dump_hierarchy(compressed=False, pretty=False).encode('utf-8')
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\session.py", line 475, in dump_hierarchy
        res.raise_for_status()
      File "C:\Users\hg\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:58622/dump/hierarchy
[E 190701 17:00:45 web:2246] 500 GET /api/v1/devices/android%3A127.0.0.1%3A7555/hierarchy (::1) 25.38ms`

**Comment by codeskyblue** [comment]
升级 uiautomator2，重新init

**Comment by shigubuhua** [comment]
现在好了，也不知哪里出的问题……

**Comment by veast** [comment]
> 现在好了，也不知哪里出的问题……

请问有做什么操作吗，我现在有台电脑上遇到了同样的问题，版本和别的可以正常使用的电脑一样...

**Comment by shigubuhua** [comment]
记不清哪步操作起作用了……
大概是，adb重启，ut2和weditor全部更新到pre版，重启电脑……

**Comment by thlengane** [comment]
This is definitely a bug, there is an issue with the dump_hierarchy() method or something. Follow the issue below..

[https://github.com/openatx/uiautomator2/issues/392](url)
