### ISSUE TITLE
V0.3.0版本启动报ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

### ISSUE THREAD

**Issue by guwenwenhappy** [openatx/weditor#62]
MacPro上运行weditor=0.3.0
listening on http://10.97.181.57:17310
[I 191012 13:16:19 web:2246] 200 GET / (::1) 6.91ms
[I 191012 13:16:19 web:2246] 304 GET /static/libs/css/buttons.css (::1) 8.55ms
[I 191012 13:16:19 web:2246] 304 GET /static/libs/fontawesome/css/font-awesome.min.css (::1) 0.87ms
[I 191012 13:16:19 web:2246] 304 GET /static/loading.svg (::1) 2.90ms
[I 191012 13:16:19 web:2246] 304 GET /static/running.svg (::1) 3.04ms
[I 191012 13:16:19 web:2246] 304 GET /static/ace/ace.js (::1) 4.71ms
[I 191012 13:16:19 web:2246] 304 GET /static/ace/mode-python.js (::1) 0.68ms
[W 191012 13:16:23 iostream:1407] SSL Error on 20 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js (::1) 3263.94ms
[W 191012 13:16:23 iostream:1407] SSL Error on 18 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[W 191012 13:16:23 iostream:1407] SSL Error on 19 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[W 191012 13:16:23 iostream:1407] SSL Error on 21 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js (::1) 3279.05ms
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js (::1) 3271.93ms
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/bootstrap/3.3.7/js/bootstrap.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/bootstrap/3.3.7/js/bootstrap.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/bootstrap/3.3.7/js/bootstrap.min.js (::1) 3279.54ms
[W 191012 13:16:23 iostream:1407] SSL Error on 18 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/bootstrap.select/1.12.2/js/bootstrap-select.min.js (::1) 244.88ms
[W 191012 13:16:23 iostream:1407] SSL Error on 18 ('14.0.44.218', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:1788] Uncaught exception GET /cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js (::1)
    HTTPServerRequest(protocol='http', host='localhost:17310', method='GET', uri='/cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/weditor/web/handlers/proxy.py", line 30, in get
        response = await self.http_client.fetch(urlpath)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 336, in run
        source_ip=source_ip,
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/tcpclient.py", line 294, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
[E 191012 13:16:23 web:2246] 500 GET /cdn.jsdelivr.net/npm/jstree@3.3.4/dist/jstree.min.js (::1) 256.64ms

**Comment by yuxinfeng** [comment]
i also have the same problem? why

**Comment by lyp0129** [comment]
我也遇到了。 帖子一：https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate，帖子二：https://blog.csdn.net/qq_25403205/article/details/81258327找到两个帖子，有提及不过我还是解决不了，有厉害的同学可以试试。
有解决的话，辛苦贴一下解决方案。

**Comment by yangeren** [comment]
在应用程序中找到·python3.7·，进入目录执行`Install Certificates.command`即可解决。@lyp0129
