### ISSUE TITLE
python 3.8 好像启动不了 

### ISSUE THREAD

**Issue by DENGXIANSHENG** [openatx/weditor#65]
PS D:\1company.project\android.uiautomator.test> python -m weditor
listening on http://192.168.1.119:17310
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\lib\site-packages\weditor\__main__.py", line 176, in <module>
    main()
  File "C:\Program Files\Python38\lib\site-packages\weditor\__main__.py", line 172, in main
    run_web(args.debug, args.port, open_browser)
  File "C:\Program Files\Python38\lib\site-packages\weditor\__main__.py", line 114, in run_web
    application.listen(port)
  File "C:\Program Files\Python38\lib\site-packages\tornado\web.py", line 2112, in listen
    server.listen(port, address)
  File "C:\Program Files\Python38\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Program Files\Python38\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Program Files\Python38\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Program Files\Python38\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

端口无法绑定？因为杀毒软件问题吗？我关闭了好像也不行，应该不是端口冲突吧，求帮忙！！

**Comment by lijinzhou2016** [comment]
我也遇到同样的问题，求解

**Comment by DENGXIANSHENG** [comment]
> 我也遇到同样的问题，求解

换成python 3.6 就好了

**Comment by JdiChen** [comment]
除了更改python版本，还有什么好的解决方法吗？

**Comment by RogerRordo** [comment]
> 除了更改python版本，还有什么好的解决方法吗？

在asyncio.py中，
`import typing
from typing import Any, TypeVar, Awaitable, Callable, Union, Optional`
之后添加
`import sys
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`

**Comment by codeskyblue** [comment]
已修复。忘了关掉了

**Comment by Sanmejie** [comment]
3.9版本有类似问题
`python -m weditor
listening on http://192.168.31.126:17310
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 255, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 251, in main
    run_web(args.debug, args.port, open_browser, args.force_quit)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\weditor\__main__.py", line 181, in run_web
    application.listen(port)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError`
