### ISSUE TITLE
cannot identify image file <_io.BytesIO object at 0x10eda08f0>

### ISSUE THREAD

**Issue by xiaoyaoamiao** [openatx/weditor#66]
Android 10
In the app, there is web page hibernate in APP.
And when that page loaded, Weditor pops error "cannot identify image file <_io.BytesIO object at 0x10eda08f0>"
Before upgrade to Android10, it was available to locate elements in hibernate web page.
After upgraded to 10, error happened.

**Comment by xiaoyaoamiao** [comment]
[I 191206 16:44:35 web:2246] 200 GET / (::1) 5.44ms
[I 191206 16:44:36 web:2246] 304 GET /api/v1/version (::1) 0.75ms
[I 191206 16:44:37 web:2246] 200 POST /api/v1/connect (::1) 124.57ms
[I 191206 16:44:39 page:297] Serial: android:CUYDU19B07003321
[W 191206 16:44:39 api:40] cannot identify image file <_io.BytesIO object at 0x1107753b0>, retrying in 0.5 seconds...
[W 191206 16:44:40 api:40] cannot identify image file <_io.BytesIO object at 0x1107753b0>, retrying in 0.6 seconds...
[W 191206 16:44:41 api:40] cannot identify image file <_io.BytesIO object at 0x1107753b0>, retrying in 0.7 seconds...
[W 191206 16:44:42 api:40] cannot identify image file <_io.BytesIO object at 0x1107753b0>, retrying in 0.7999999999999999 seconds...
Traceback (most recent call last):
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/weditor/web/handlers/page.py", line 301, in get
    d.screenshot().convert("RGB").save(buffer, format='JPEG')
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/weditor/web/device.py", line 28, in screenshot
    return self._d.screenshot()
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/uiautomator2/__init__.py", line 1280, in screenshot
    return self.session().screenshot(*args, **kwargs)
  File "</Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/decorator.py:decorator-gen-6>", line 2, in screenshot
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/uiautomator2/session.py", line 483, in screenshot
    return Image.open(buff)
  File "/Users/miaog001/Documents/AutoProject/autoapp/virtualEnv/venv3_ui2/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))

**Comment by starplanet** [comment]
I have the same problem. Do you solve it?
